schema/init_schema.sql

feat: design initial data models

---

schema/init_schema.sql

변경사항: users 테이블에 school 컬럼 추가
참고사항: main 브랜치 최신 커밋 기준으로 rebase 완료

fix: add school column to users table

---

Dockerfile.local
build.gradle
docker-compose.yml
watch-and-reload.sh

task-x-x-x
Spring 서버 로컬 컨테이너 hot-reload를 지원해요.

env: add hot-reload support

---

flyway/migrations/V3__add_contents_generated_at_and_remove_unused_column.sql

task-0-4-7
퀴즈, 시험 생성 여부 확인을 위해 컨텐츠 생성 날짜 컬럼을 추가하고 quizzes에서 불필요한 컬럼을 제거해요.

refactor: add contents_generated_at col and remove unused col

---

watch-and-reload.sh

task-x-x-x
Hot-reload시 파일 생성 기준으로 하니까 조금 불안정해서 해시 기반으로 수정해요.

chore: make the reload more stable

---

src/main/java/com/example/api/entity/CourseActivityLog.java
src/main/java/com/example/api/entity/ExamResponse.java
src/main/java/com/example/api/entity/SchoolCalendar.java

fix: inconsistent column types

---

src/main/java/com/example/api/entity/Exam.java
src/main/java/com/example/api/entity/Quiz.java

task-x-x-x
sql(v3)의 수정 사항을 Quiz와 Exam 엔티티 코드에 적용했습니다.

fix: entity of Quiz and Exam

---

src/main/java/com/example/api/controller/CourseController.java
src/main/java/com/example/api/controller/SemesterController.java
src/main/java/com/example/api/controller/dto/semester/CreateSemesterRequest.java
src/main/java/com/example/api/controller/dto/semester/SemesterListResponse.java
src/main/java/com/example/api/controller/dto/semester/SemesterResponse.java
src/main/java/com/example/api/controller/dto/semester/UpdateSemesterDatesRequest.java
src/main/java/com/example/api/controller/dto/semester/UpdateSemesterGradesRequest.java
src/main/java/com/example/api/controller/dto/semester/UpdateSemesterRequest.java
src/main/java/com/example/api/entity/enums/Season.java
src/main/java/com/example/api/service/SemesterService.java
src/main/java/com/example/api/service/SemesterServiceImpl.java
src/main/java/com/example/api/service/dto/semester/CreateSemesterInput.java
src/main/java/com/example/api/service/dto/semester/SemesterListOutput.java
src/main/java/com/example/api/service/dto/semester/SemesterOutput.java
src/main/java/com/example/api/service/dto/semester/UpdateSemesterDatesInput.java
src/main/java/com/example/api/service/dto/semester/UpdateSemesterGradesInput.java
src/main/java/com/example/api/service/dto/semester/UpdateSemesterInput.java
src/test/java/com/example/api/controller/CourseControllerTest.java
src/test/java/com/example/api/controller/SemesterControllerTest.java
src/test/java/com/example/api/service/CourseServiceTest.java
src/test/java/com/example/api/service/SemesterServiceTest.java

task-2-2-3
Semester controller/service DTO를 분리해요.

refactor: separate the DTOs for semesters

---

src/test/java/com/example/api/controller/LectureControllerTest.java

LectureController쪽  유닛 테스트 데이터 잘못된 부분 수정해요.

fix: typo in test

---

flyway/migrations/V4__add_parsed_text_to_lecture_table.sql

fix: schema

---

Makefile
jobs/generate_quiz/handler.py
jobs/generate_quiz/openai_client.py
jobs/generate_quiz/quiz_models.py
jobs/generate_quiz/requirements.txt
jobs/test_env/README.md
jobs/test_env/docker-compose.test.yml
jobs/test_env/run_test_job.py
jobs/test_env/samples/sample_event_quiz.json
prompts/generate_quiz/v1.yaml

- 4-1-4
- 4-1-5
- 비동기 퀴즈 생성용 Lambda Job을 구현해요.

feat(jobs): add job for generating quizzes

---

.env.example
.gitignore
build.gradle
docker-compose.yml
src/main/java/com/example/api/config/StorageConfig.java
src/main/java/com/example/api/controller/StorageController.java
src/main/java/com/example/api/service/MinioStorageService.java
src/main/java/com/example/api/service/S3StorageService.java
src/main/java/com/example/api/service/StorageService.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/test/java/com/example/api/controller/StorageControllerTest.java
src/test/java/com/example/api/service/MinioStorageServiceTest.java
src/test/java/com/example/api/service/S3StorageServiceTest.java
src/test/java/com/example/api/service/StorageServiceTest.java

task-2-16-4
S3와 MinIO에서의 업로드 기능을 구현해요.

feat: implement s3 and minio upload

---

src/main/java/com/example/api/controller/CourseController.java
src/test/java/com/example/api/controller/CourseControllerTest.java

task-x-x-x
Request class 오타 수정해요

fix: wrong request class

---

src/main/java/com/example/api/config/SecurityConfig.java

feat: add CORS configuration code to SecurityConfig

---

.gitignore
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml

task-x-x-x
dev용 ECS task 정의를 위해 application-dev.yml을 만들어요.

chore(hotfix): add application-dev.yml and modify .gitignore

---

Dockerfile.prod
src/main/java/com/example/api/config/SecurityConfig.java
src/main/java/com/example/api/config/StorageConfig.java
src/main/java/com/example/api/controller/HealthController.java
src/main/java/com/example/api/service/S3StorageService.java

task-x-x-x
api-server 이미지 빌드 오류 해결 위해 
1. s3 관련 빈 등록
2. Dockerfile.prod gradle 관련 수정 (확인해주시면 감사하겠습니다)
3. health check를 위한 controller 추가 (Dockerfile.prod에 나와있는 엔드포인트 구현)
일단은 해당 코드 반영한 이미지로 배포했습니다.

fix(hotfix): fix api-server image build errors and add health check endpoint

---

src/main/java/com/example/api/controller/BaseController.java
src/main/java/com/example/api/controller/CourseController.java
src/main/java/com/example/api/controller/LectureController.java
src/main/java/com/example/api/controller/SemesterController.java
src/main/java/com/example/api/controller/StorageController.java
src/main/java/com/example/api/exception/GlobalExceptionHandler.java
src/test/java/com/example/api/config/TestSecurityConfig.java
src/test/java/com/example/api/controller/CourseControllerTest.java
src/test/java/com/example/api/controller/LectureControllerTest.java
src/test/java/com/example/api/controller/SemesterControllerTest.java
src/test/java/com/example/api/controller/StorageControllerTest.java
src/test/java/com/example/api/util/WithMockUser.java

task-0-4-18
Placeholder user id를 없애고 실제 인증된 유저를 사용하도록 수정해요.

refactor(auth): use authenticated users instead of test user

---

jobs/generate_quiz/handler.py
jobs/summarize_lecture/handler.py
jobs/test_env/run_test_job.py

task-x-x-x
요약시 course_id와 user_id를 가져오기 위해 lecture_info를 가져오는 로직을 제거하고 큐로부터 받도록 수정해요.

perf: remove unncessary query and clean up

---

src/main/resources/schemas/sqs/generate_exam.json
src/main/resources/schemas/sqs/generate_quiz.json
src/main/resources/schemas/sqs/generate_summary.json

task-0-4-6 (re-upload)
이전에 커밋 겹쳤던 것 때문에 task-0-4-6을 다시 PR하는 점 양해 부탁드립니다.
각 스키마의 전달 값이 올바른지, 유용한지 체크해주세요.

feat: add sqs schemas for generation

---

.github/workflows/deploy/dev/deploy-summarize-lecture.yml
.github/workflows/deploy/prod/deploy-summarize-lecture.yml

task-0-4-13
Dev, Prod 요약 Lambda Job 배포 Job을 추가해요.

cd(lambda): add a job to deploy lecture summarization Lambda job

---

.github/workflows/deploy/dev/deploy-generate-exam.yml
.github/workflows/deploy/prod/deploy-generate-exam.yml
README.md
jobs/README.md

task-0-4-15
Dev, Prod 시험 생성 Lambda Job 배포 Job을 추가해요.

cd(lambda): add a job to deploy exam generation Lambda job

---

.github/workflows/deploy/dev/deploy-generate-quiz.yml
.github/workflows/deploy/prod/deploy-generate-quiz.yml
jobs/generate_quiz/README.md

task-0-4-14
Dev, Prod 퀴즈 생성 Lambda Job 배포 Job을 추가해요.

cd(lambda): add a job to deploy quiz generation Lambda job

---

.github/workflows/migrations/dev/migrate.yml
.github/workflows/migrations/prod/migrate.yml
README.md

task-0-4-17
Dev, Prod용 DB 마이그레이션 Job을 추가해요.
- Repository secrets 설정
- Bastion 서버 생성 및 설정

cd(migration): add jobs for db migrations

---

README.md

docs: update migration section

---

src/main/java/com/example/api/controller/HealthController.java
src/main/java/com/example/api/controller/LectureController.java

style: add missing tag and unify the styles

---

README.md
jobs/README.md

docs: add lambda job test section

---

flyway/migrations/V5__change_parsed_text_type_to_jonsb.sql
jobs/summarize_lecture/handler.py
jobs/summarize_lecture/parsed_text_models.py
jobs/test_env/setup_test_db.py
src/main/java/com/example/api/controller/dto/lecture/LectureResponse.java
src/main/java/com/example/api/entity/Lecture.java
src/main/java/com/example/api/entity/ParsedPage.java
src/main/java/com/example/api/entity/ParsedText.java
src/main/java/com/example/api/service/dto/lecture/LectureOutput.java
src/test/java/com/example/api/controller/LectureControllerTest.java
src/test/java/com/example/api/service/LectureServiceTest.java

task-3-2-5
parsed_text의 스키마를 디자인해요.
```json
{
"total_pages": "<총 페이지 수>"
"pages": [
{
"page_number": "<페이지 번호>",
"text": "<슬라이드 내용>"
}
]
}
```

refactor: design the parsed_text schema

---

Makefile
jobs/generate_quiz/handler.py
jobs/generate_quiz/parsed_text_models.py
jobs/test_env/README.md
jobs/test_env/docker-compose.test.yml
jobs/test_env/run_test_job.py
jobs/test_env/setup_test_db.py
src/main/resources/schemas/sqs/generate_quiz.json

task-4-1-8
퀴즈 생성시 Lecture의 `parsed_text`를 사용하도록 수정해요.

refactor(jobs/quiz): use parsed_text to create quizzes

---

jobs/summarize_lecture/handler.py
jobs/summarize_lecture/openai_client.py
jobs/summarize_lecture/summary_models.py
prompts/summarize_lecture/v2.yaml

task-x-x-x
강의 요약 Prompt를 개선해요.
- 슬라이드 처리 가이드라인 추가
- Topic / sub topic 기준 추가
- Description, details 가이드 추가
- 수식, 표, 언어 관련 지침 추가

feat(prompt): upgrade lecture summarization prompt

---

src/main/java/com/example/api/config/StorageConfig.java
src/main/java/com/example/api/controller/LectureController.java
src/main/java/com/example/api/controller/dto/lecture/LectureResponse.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/test/java/com/example/api/controller/LectureControllerTest.java

task-3-2-7
Lecture 내릴 때 material full url을 내리도록 수정해요.

refactor: return full url of lecture material

---

jobs/summarize_lecture/handler.py
jobs/summarize_lecture/openai_client.py
jobs/summarize_lecture/pdf_chunker.py
jobs/summarize_lecture/requirements.txt
jobs/test_env/Dockerfile.test
jobs/test_env/docker-compose.test.yml
jobs/test_env/run_test_job.py
jobs/test_env/setup_test_db.py
prompts/summarize_lecture/v2.yaml

task-2-18-8
PDF 슬라이드가 많을 경우 GPT-4o API의 max tokens 때문에 일부 내용이 과하게 생략되어 퀄리티가 매우 낮아지는 케이스가 있어요. PDF를 적절한 사이즈로 split해서 각 chunk를 parallel하게 summarize해서 merge 하는 전략으로 수정합니다.

feat(jobs/summarization): split and summarize the lecture content in parallel for better quality

---

src/main/resources/application-dev.yml

task-x-x-x
데모를 위해 dev 서버 jwt acc token ttl을 잠시 늘려놔요

config: make acc token ttl very long temporariily

---

src/main/java/com/example/api/controller/LectureController.java
src/main/java/com/example/api/controller/dto/lecture/UpdateLectureRequest.java
src/main/java/com/example/api/service/LectureServiceImpl.java
src/main/java/com/example/api/service/dto/lecture/UpdateLectureInput.java
src/test/java/com/example/api/controller/LectureControllerTest.java
src/test/java/com/example/api/service/LectureServiceTest.java

task-x-x-x
강의 업데이트 (lecture update) 에서 material path/type 제거했습니다.

fix: Lecture update

---

jobs/generate_exam/Dockerfile
jobs/generate_quiz/Dockerfile
jobs/summarize_lecture/Dockerfile

hotfix(jobs): copy all py while building image

---

jobs/summarize_lecture/handler.py
src/main/java/com/example/api/adapters/sqs/SQSClientImpl.java

task-x-x-x
SQS 메시지 전송시 snake_case를 사용해요.

hotfix(sqs): use snake case to send messages

---

.github/workflows/deploy-api-server-dev.yml

task-x-x-x
Langchain-server 배포를 추가해요.

cd(api): add internal langchain-server deploy

---

src/main/java/com/example/api/config/SecurityConfig.java

task-x-x-x
ALB 도메인을 CORS allowed origin에 추가해요.

fix: add ALB domain to CORS allowed origins

---

src/main/java/com/example/api/config/SecurityConfig.java
src/main/java/com/example/api/controller/AuthController.java
src/main/java/com/example/api/security/jwt/JwtAuthenticationFilter.java
src/main/java/com/example/api/security/jwt/JwtProvider.java
src/main/java/com/example/api/service/AuthService.java
src/main/java/com/example/api/service/AuthServiceImpl.java
src/test/java/com/example/api/controller/AuthControllerTest.java
src/test/java/com/example/api/service/AuthServiceTest.java

task-x-x-x
/auth/me 오류 해결해요
-JWT filter의 authentication type과 controller, service에서의 타입 일치
-SecurityConfig 권한 OPTIONS 관리

fix: resolve error in /auth/me by aligning authentication types across JWT filter, controller, and service

---

src/main/java/com/example/api/controller/BaseController.java
src/main/java/com/example/api/security/jwt/JwtAuthenticationFilter.java
src/test/java/com/example/api/util/WithMockUser.java

task-x-x-x
Principal 타입이 다른 문제를 수정해요

fix(auth): type mismatch issue

---

src/main/java/com/example/api/controller/dto/lecture/LectureResponse.java
src/main/java/com/example/api/controller/dto/lecture/summary/Keyword.java
src/main/java/com/example/api/controller/dto/lecture/summary/Metadata.java
src/main/java/com/example/api/controller/dto/lecture/summary/PageRange.java
src/main/java/com/example/api/controller/dto/lecture/summary/Summary.java
src/main/java/com/example/api/controller/dto/lecture/summary/TopicDetails.java
src/test/java/com/example/api/controller/LectureControllerTest.java

task-4-3-2
summary model이 생성하는 데이터의 Dto를 작성했습니다.
지금 LectureResponse.java에 추가된 함수에 캐스팅이 사용되고 있는데 좀 더 안전한 방법을 사용해야 하는지 확인바랍니다.

feat: Add Summary Dto

---

.github/workflows/migration-dev.yml
.github/workflows/migration-prod.yml
Makefile

task-x-x-x
Resolve https://github.com/Study-AID/study-AID-backend/issues/81
Migration 도중 checksum mismatch 에러 발생시 repair하는 스텝을 추가해요.

refactor: add migration repair step

---

jobs/generate_exam/handler.py
jobs/generate_quiz/handler.py
jobs/summarize_lecture/handler.py
jobs/summarize_lecture/openai_client.py
jobs/summarize_lecture/parsed_text_models.py
jobs/summarize_lecture/summary_models.py

task-2-18-10
- Retry 로직을 간소화하고 min interval을 늘려요.
- jobs 핸들러 코드들 스타일을 통일해요.

refactor(jobs): simplify the retry logics and unify styles

---

src/main/java/com/example/api/controller/LectureController.java
src/main/java/com/example/api/controller/dto/lecture/LecturePreviewResponse.java
src/main/java/com/example/api/controller/dto/lecture/LectureResponse.java
src/test/java/com/example/api/controller/LectureControllerTest.java

task-5-1-3
모의고사 강의 선택시 미리보기 렌더링할 때 사용할 GetLecturePreview API를 추가해요.

feat: implement GetLecturePreview API

---

.github/workflows/migration-dev.yml

task-x-x-x
checksum mismatch 확인이 불필요한 조건인듯해서 없애요.

fix(cd/migration): remove condition

---

src/main/java/com/example/api/controller/CourseAssessmentController.java
src/main/java/com/example/api/controller/dto/courseAssessment/CourseAssessmentListResponse.java
src/main/java/com/example/api/controller/dto/courseAssessment/CourseAssessmentResponse.java
src/main/java/com/example/api/controller/dto/courseAssessment/CreateCourseAssessmentRequest.java
src/main/java/com/example/api/controller/dto/courseAssessment/UpdateCourseAssessmentRequest.java
src/main/java/com/example/api/repository/CourseAssessmentRepositoryCustom.java
src/main/java/com/example/api/repository/CourseAssessmentRepositoryImpl.java
src/main/java/com/example/api/service/CourseAssessmentService.java
src/main/java/com/example/api/service/CourseAssessmentServiceImpl.java
src/main/java/com/example/api/service/dto/courseAssessment/CourseAssessmentListOutput.java
src/main/java/com/example/api/service/dto/courseAssessment/CourseAssessmentOutput.java
src/main/java/com/example/api/service/dto/courseAssessment/CreateCourseAssessmentInput.java
src/main/java/com/example/api/service/dto/courseAssessment/UpdateCourseAssessmentInput.java
src/test/java/com/example/api/controller/CourseAssessmentControllerTest.java
src/test/java/com/example/api/repository/CourseAssessmentRepositoryTest.java
src/test/java/com/example/api/service/CourseAssessmentServiceTest.java

task-2-12-2
과제 성과 CRUD api 코드입니다.
현재 업데이트를 하나의 메서드로 수행 중인데 title과 점수 업데이트를 분리할 필요가 있을지 궁금합니다.

feat: Course Assessment CRUD API

---

src/main/java/com/example/api/controller/ReportController.java
src/main/java/com/example/api/controller/dto/report/CreateReportRequest.java
src/main/java/com/example/api/controller/dto/report/ReportListResponse.java
src/main/java/com/example/api/controller/dto/report/ReportResponse.java
src/main/java/com/example/api/repository/ExamQuestionReportRepositoryCustom.java
src/main/java/com/example/api/repository/ExamQuestionReportRepositoryImpl.java
src/main/java/com/example/api/repository/QuizQuestionReportRepository.java
src/main/java/com/example/api/repository/QuizQuestionReportRepositoryCustom.java
src/main/java/com/example/api/repository/QuizQuestionReportRepositoryImpl.java
src/main/java/com/example/api/service/ExamQuestionReportService.java
src/main/java/com/example/api/service/ExamQuestionReportServiceImpl.java
src/main/java/com/example/api/service/QuizQuestionReportService.java
src/main/java/com/example/api/service/QuizQuestionReportServiceImpl.java
src/main/java/com/example/api/service/dto/quiz/CreateQuizQuestionReportInput.java
src/main/java/com/example/api/service/dto/quiz/QuizQuestionReportOutput.java
src/main/java/com/example/api/service/dto/report/CreateExamQuestionReportInput.java
src/main/java/com/example/api/service/dto/report/CreateQuizQuestionReportInput.java
src/main/java/com/example/api/service/dto/report/ExamQuestionReportOutput.java
src/main/java/com/example/api/service/dto/report/QuizQuestionReportOutput.java
src/test/java/com/example/api/controller/ReportControllerTest.java
src/test/java/com/example/api/repository/ExamQuestionReportRepositoryTest.java
src/test/java/com/example/api/repository/QuizQuestionReportRepositoryTest.java
src/test/java/com/example/api/service/ExamQuestionReportServiceTest.java
src/test/java/com/example/api/service/QuizQuestionReportServiceTest.java

task-4-4-2
task-5-4-2
퀴즈/시험 아이템 신고 기능입니다. 컨트롤러를 하나로 통합하여 퀴즈/시험 아이템 신고를 한 곳에서 이루어지게 할 수 있도록 구현했습니다. 다만 프론트에서 해당 신고 아이템이 퀴즈 아이템인지, 시험 아이템인지는 알려줘야 합니다.

feat: add quiz/exam question report 

---

src/main/java/com/example/api/controller/LectureController.java
src/main/java/com/example/api/controller/dto/lecture/UpdateLectureNoteRequest.java
src/main/java/com/example/api/repository/LectureRepository.java
src/main/java/com/example/api/service/LectureService.java
src/main/java/com/example/api/service/LectureServiceImpl.java
src/main/java/com/example/api/service/dto/lecture/UpdateLectureNoteInput.java
src/test/java/com/example/api/controller/LectureControllerTest.java
src/test/java/com/example/api/service/LectureServiceTest.java

task-3-1-3
필기 내용을 업데이트합니다.
/v1/lectures/{id}로 GET 요청을 보내면 강의 세부 조회가 되기 때문에 Note만을 위한 조회 기능을 따로 만들지 않았습니다. 만약 필요하다고 판단되시면 만들겠습니다.

feat: add note update

---

jobs/generate_exam/handler.py
jobs/generate_quiz/handler.py
jobs/summarize_lecture/handler.py

task-x-x-x
SES 프로덕션 승인 조건에 따라 unsubscribe option을 메일에 명시해요.
+메일 제목 오타 수정, 이모티콘 수정
(아직 unsubscribe 텍스트만 추가하고 링크는 넣지 않았어요.)

chore: add unsubscribe option to email template and modify style

---

src/main/java/com/example/api/controller/CourseController.java
src/main/java/com/example/api/controller/ExamController.java
src/main/java/com/example/api/controller/LectureController.java
src/main/java/com/example/api/controller/QuizController.java
src/main/java/com/example/api/controller/SemesterController.java
src/main/java/com/example/api/service/CourseServiceImpl.java
src/main/java/com/example/api/service/ExamServiceImpl.java
src/main/java/com/example/api/service/LectureServiceImpl.java
src/main/java/com/example/api/service/QuizServiceImpl.java
src/main/java/com/example/api/service/SemesterServiceImpl.java
src/test/java/com/example/api/service/CourseServiceTest.java
src/test/java/com/example/api/service/ExamServiceTest.java
src/test/java/com/example/api/service/LectureServiceTest.java
src/test/java/com/example/api/service/QuizServiceTest.java
src/test/java/com/example/api/service/SemesterServiceTest.java

task-x-x-x
Partial update가 되지 않던 문제를 해결해요. Controller에서도 조회가 한 번 일어나서 현재 2 get / 1 set이 되고 있어서 비효율적인데 service DTO가 전체 entity를 담고 있진 않아서 그대로 사용하기가 어려운 상황이라 우선 이대로 진행했어요. Service DTO를 변경해도 되는데 수정 범위가 너무 커져서 먼저 이렇게 대응합니다.

fix: bug that wrong partial update

---

src/main/java/com/example/api/service/dto/quiz/QuizResultElement.java
src/test/java/com/example/api/service/QuizServiceTest.java

task-x-x-x
QuizResultElement의 불필요한 null set을 지우고 기타 수정사항을 적용했습니다.

fix: delete null set in QuizResultElement

---

src/main/java/com/example/api/controller/dto/exam/ExamResultResponse.java
src/main/java/com/example/api/controller/dto/quiz/QuizResultResponse.java
src/main/java/com/example/api/entity/ExamResult.java
src/main/java/com/example/api/entity/QuizResult.java
src/main/java/com/example/api/service/ExamServiceImpl.java
src/main/java/com/example/api/service/dto/exam/ExamResultOutput.java
src/main/java/com/example/api/service/dto/quiz/QuizResultOutput.java
src/test/java/com/example/api/controller/ExamControllerTest.java
src/test/java/com/example/api/controller/QuizControllerTest.java
src/test/java/com/example/api/service/ExamServiceTest.java
src/test/java/com/example/api/service/QuizServiceTest.java

task-x-x-x
시험 생성 시 reference lecture 저장이 누락된 것을 수정합니다.
핫픽스라 바로 머지합니다

Fix: create exam

---

flyway/migrations/V16__update_exam_table_index.sql
jobs/generate_exam/handler.py
src/main/java/com/example/api/entity/Exam.java

task-x-x-x
Exam.java에 index를 추가하고 generate_exam handler에서 시험 생성이 아닌 퀴즈처럼 업데이트하는 방식으로 수정했습니다.

fix: update schima and exam job handler
